# Test job

on: push

jobs:
  lint:
  name: Lint
  runs-on: ubuntu-latest
  steps:
    -uses: Satyavanikk/mygactions@v1
  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      -uses: Satyavanikk/mygactions@v1

    
